### ISSUE TITLE
Point to location of tutorials zips

### ISSUE THREAD

**Issue by idhugoid** [INTO-CPS-Association/training#2]
On Tutorial 1 Step 3 on Page 2 and in the others, it should be pointed that the zips for the tutorials are "in a private SVN repo for the members of the association"

**Comment by rudi** [comment]
Would it be possible to make the tutorial material available for non-members?  Having a step-by-step tutorial offered by the project but not being able to actually follow it is such a tease ;)

**Comment by idhugoid** [comment]
@pglvdm this is your call.

**Comment by pglvdm** [comment]
well the reason why we placed it there is that the files are too large to be placed at GitHub. In principles I have no problem in moving it out of a private repo but I think that it will be an advantage to have at least some artefacts that you only get access to as a member.

**Comment by rudi** [comment]
In the into-cps app, there's "File -> Import Example Project", which offers the Single-tank Water Tank case study, maybe the tutorial can use this one?  (I say this, fully well knowing that no one asked to get the task of rewriting tutorial documents)

**Comment by clagms** [comment]
@rudi we have tutorials that are much less in-depth to the INTO-CPS APP, but whose materials have been made public, and can get you started quickly.
See for instance: https://www.youtube.com/watch?v=8SMO9RqmwKE&ab_channel=INTO-CPSAssociation
(The description includes links to publicly available materials).

**Comment by rudi** [comment]
@clagms thanks for the info! The reason I'm working with these tutorials is that they are prominently listed on the homepage of into-cps.org, and are one click away.  If these tutorials should not be used by people interested in the toolchain, the alternative tutorials you give should be advertised on the homepage instead.

(As a personal remark, I have been disappointed by prerecorded video tutorials so many times for so many different reasons that I'm quite hesitant to even click "Play".)

**Comment by clagms** [comment]
I think this is fixed with https://github.com/INTO-CPS-Association/training/commit/d694541b1ab3bc4348bbf28f23b2ec3accf68a2e .
Reopen if you disagree.
