### ISSUE TITLE
Remove Java 1.8 requirement from Tutorial 0 and maybe elsewhere

### ISSUE THREAD

**Issue by idhugoid** [INTO-CPS-Association/training#3]
Previously Maestro required Java 1.8. It works with more recent versions now. @CThuleHansen or @lausdahl  we list Java 11 as a dependency to build. Can you point to which Java version is required to run the latest COE version?

As this causes a bit of trouble, it would be nice to update the COE required version in the tutorials as well.

**Comment by CThuleHansen** [comment]
java8 - java 11 should be sufficient to run the latest COE version. 
java13 has not been tested yet.

**Comment by clagms** [comment]
Closed with https://github.com/INTO-CPS-Association/training/commit/797e631f360ce93f46cd8ada6cf50f3c1f7268e8
